# Copyright (c) 2023 The Songlin Yang Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Bug Report
description: Report a bug encountered while using this project
labels:
- type/bug
body:
- type: markdown
  attributes:
    value: |
      Please fill the form below and provide as much information as possible.
      Not doing so may result in your bug not being addressed in a timely manner.

- type: textarea
  id: problem
  attributes:
    label: What happened?
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: What did you expect to happen?
  validations:
    required: true

- type: textarea
  id: repro
  attributes:
    label: How can we reproduce it (as minimally and precisely as possible)?
  validations:
    required: true

- type: textarea
  id: additional
  attributes:
    label: Anything else we need to know?

- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
